//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_House
{
    using System;
    using System.Collections.Generic;
    
    public partial class Книги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Книги()
        {
            this.Книги_в_аренде = new HashSet<Книги_в_аренде>();
            this.Поставки = new HashSet<Поставки>();
            this.Списание_книг = new HashSet<Списание_книг>();
        }
    
        public int id { get; set; }
        public string Название { get; set; }
        public int Жанр { get; set; }
        public int Цена { get; set; }
        public string Комментарий { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Автор { get; set; }
    
        public virtual Авторы Авторы { get; set; }
        public virtual Жанры Жанры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Книги_в_аренде> Книги_в_аренде { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставки> Поставки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Списание_книг> Списание_книг { get; set; }
    }
}
