//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_House
{
    using System;
    using System.Collections.Generic;
    
    public partial class Списание_книг
    {
        public int id { get; set; }
        public Nullable<int> id_Книги { get; set; }
        public int Количество { get; set; }
        public string Причина { get; set; }
        public Nullable<int> id_сотрудника { get; set; }
    
        public virtual Книги Книги { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }

        public Списание_книг(int id, int id_Книги, int Количество, string Причина, int id_сотрудника)
        {
            this.id = id;
            this.id_Книги = id_Книги;
            this.Количество = Количество;
            this.id_сотрудника = id_сотрудника;
            this.Причина = Причина;
        }
        public Списание_книг() { }
    }
}
